from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=True)
    mobile = db.Column(db.String(15), unique=True, nullable=False)
    password_hash = db.Column(db.String(200))
    role = db.Column(db.String(20), default='staff')
    status = db.Column(db.String(20), default='pending')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    last_login = db.Column(db.DateTime)

class Customer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    mobile = db.Column(db.String(15), unique=True, nullable=False)
    alt_phone = db.Column(db.String(15))
    address = db.Column(db.Text)
    area = db.Column(db.String(100))
    site_name = db.Column(db.String(200))
    architect_name = db.Column(db.String(100))
    referred_by = db.Column(db.String(50))
    budget_range = db.Column(db.String(50))
    notes = db.Column(db.Text)
    status = db.Column(db.String(20), default='new_inquiry')
    assigned_staff_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(50), unique=True, nullable=False, index=True)
    code_norm = db.Column(db.String(50), index=True)
    description = db.Column(db.Text)
    desc_norm = db.Column(db.Text, index=True)
    ewp = db.Column(db.Float, default=0)
    mdp = db.Column(db.Float, default=0)
    sdp = db.Column(db.Float, default=0)
    npp = db.Column(db.Float, default=0)
    nrp = db.Column(db.Float, default=0)
    mrp = db.Column(db.Float, default=0)
    old_nrp = db.Column(db.Float, default=0)
    old_mrp = db.Column(db.Float, default=0)
    source = db.Column(db.String(20))

class Quotation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    quotation_number = db.Column(db.String(20), unique=True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable=True)
    created_by_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    pricing_mode = db.Column(db.String(10))
    discount_percent = db.Column(db.Float, default=0)
    show_discount = db.Column(db.Boolean, default=False)
    show_gst = db.Column(db.Boolean, default=True)
    gst_percent = db.Column(db.Float, default=18)
    show_images = db.Column(db.Boolean, default=True)
    status = db.Column(db.String(20), default='draft')
    subtotal = db.Column(db.Float, default=0)
    discount_amount = db.Column(db.Float, default=0)
    gst_amount = db.Column(db.Float, default=0)
    grand_total = db.Column(db.Float, default=0)
    notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)
    bathrooms = db.relationship('Bathroom', backref='quotation', lazy=True, cascade="all, delete-orphan")

class Bathroom(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    quotation_id = db.Column(db.Integer, db.ForeignKey('quotation.id'))
    name = db.Column(db.String(100))
    order_index = db.Column(db.Integer, default=0)
    areas = db.relationship('BathroomArea', backref='bathroom', lazy=True, cascade="all, delete-orphan")

class BathroomArea(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    bathroom_id = db.Column(db.Integer, db.ForeignKey('bathroom.id'))
    area_type = db.Column(db.String(50))
    order_index = db.Column(db.Integer, default=0)
    items = db.relationship('QuotationItem', backref='area', lazy=True, cascade="all, delete-orphan")

class QuotationItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    area_id = db.Column(db.Integer, db.ForeignKey('bathroom_area.id'))
    product_code = db.Column(db.String(50), nullable=True)
    description = db.Column(db.Text)
    quantity = db.Column(db.Integer, default=1)
    unit_price = db.Column(db.Float, default=0)
    total_price = db.Column(db.Float, default=0)
    is_custom = db.Column(db.Boolean, default=False)
    custom_name = db.Column(db.String(200), nullable=True)
    image_url = db.Column(db.Text, nullable=True)
    label = db.Column(db.String(200), nullable=True)
    delivery_status = db.Column(db.String(20), default='pending')
    order_index = db.Column(db.Integer, default=0)

class Visit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable=True)
    visitor_name = db.Column(db.String(100))
    phone = db.Column(db.String(15))
    purpose = db.Column(db.String(100))
    visit_type = db.Column(db.String(50))
    check_in = db.Column(db.DateTime, default=datetime.utcnow)
    check_out = db.Column(db.DateTime)
    remarks = db.Column(db.Text)

class FollowUp(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customer.id'))
    assigned_to_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    scheduled_date = db.Column(db.DateTime)
    followup_type = db.Column(db.String(50))
    notes = db.Column(db.Text)
    status = db.Column(db.String(20), default='pending')
    completed_at = db.Column(db.DateTime)
    completed_notes = db.Column(db.Text)

class ActivityLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    action = db.Column(db.String(50))
    entity_type = db.Column(db.String(50))
    entity_id = db.Column(db.Integer)
    details = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
